### ISSUE TITLE
[Anathema 1.9] Silithid Carapace Fragment are still Soulbound + Drop 1 / kill instead of 1-3

### ISSUE THREAD

**Issue by Slicy** [elysium-project/itemization#11]
As per staff decision the Silithid Carapace Fragments were Soulbound / BoP before the Gates of Anh' Qiraj opened.

The Gates are now opened and the Silithid Carapace Fragments are still Soulbound / BoP instead of becoming unbound.

_"Silithid Carapace Fragments will be group-dropped, but will be bind on pickup, so the player attempting to complete the quest line MUST BE PRESENT  in killing the mobs. **(All Silithid Carapace Fragments will be unbound after the opening of the gates.)** "_

https://forum.elysium-project.org/topic/40557-the-gates-of-ahn%E2%80%99qiraj/

SIDE ISSUE ABOUT COUNT OF CARAPACE FRAGMENTS DROP / MOB KILLED.

Elite mobs in Hives are dropping only 1 Silithid Carapace Fragment per kill again. This is was fixed to 1-3 carapace framgents drop for each Hive, with a 10% of getting an extra carapace fragment from Hive'Regal mobs.

Perhaps it belongs here ? https://github.com/elysium-project/server/blob/8113b60c86e43f6698459924540264ede2ac91f6/sql/migrations/20170405065838_world.sql

**Comment by m-laniakea** [comment]
As you said, it was a staff decision. It's not handled in this repository.
