### ISSUE TITLE
Flarecore Gloves soulbound: Confirmed

### ISSUE THREAD

**Issue by QAkvastskaft** [elysium-project/itemization#13]
BUGGED BEHAVIOR
Hi dear GM. [Pattern: Flarecore Gloves] - Binds when equipped, but when i create gloves, they soulbound in the backpack. I didn't equiped it. I create one more, but second gloves still soulbound.

Can u help me pls?

 CORRECT BEHAVIOR
[Pattern: Flarecore Gloves] - Binds when equipped. Not soulbound

 SOURCES
Atlas, http://db.vanillagaming.org/?item=17018

Comment from QAiblis:
Should be BoP until patch 1.7 
Flarecore Gloves now bind when equipped.
Source:
https://web.archive.org/web/20080915204524/http://www.worldofwarcraft.com/patchnotes/patch1p7.html

Original post on bug tracker here: https://elysium-project.org/bugtracker/issue/2847

**Comment by QAkvastskaft** [comment]
Summary:
Item 17018 should be made BoE with patch 1.7

**Comment by m-laniakea** [comment]
@QAkvastskaft You meant item 16979?

**Comment by QAkvastskaft** [comment]
Yes, my bad
