### ISSUE TITLE
How do i find armor values for raid bosses in the source code?

### ISSUE THREAD

**Issue by omakaroni** [elysium-project/itemization#16]
How do i find armor values for raid bosses in the source code?

**Comment by AlisterGreg** [comment]
armour values aren't found in the source code, they are stored in the database. as this is on the Itemisation project ill assume you mean in the database, this query will return the armour of a creature ``` Select armor from creature_template where `name`= 'onyxia'```

**Comment by omakaroni** [comment]
im trying to figure the armor values on all the raid bosses form ony and MC - naxx, if you know a way to do this, and could send me a list, this would be of huge help to me. Im currently developing a spreadsheet to calculate fury warriors dps

**Comment by AlisterGreg** [comment]
Give me a min 👍

**Comment by omakaroni** [comment]
some bosses like C'thun have 2 stages and maybe 2 different armor values, like Eye of Cthun and body of Cthun, if thats the case plz include that aswell. Thanks for helping me out here :)

**Comment by AlisterGreg** [comment]
![image](https://cloud.githubusercontent.com/assets/16710508/26507215/3f277f98-4247-11e7-9b17-a8204f48e998.png)

this is the best i can offer, my database is pretty out of date

**Comment by omakaroni** [comment]
ye that looks like the DB-vanilla ones, and staden already confirmed those are not the ones used at anathema today, anyways thanks for the effort you put in :)
