### ISSUE TITLE
How should we use itemization sql files ?

### ISSUE THREAD

**Issue by Cylae** [elysium-project/itemization#2]
Hello,

First, thank you for bringing us your work.

As the title said : How should we use itemization sql files ?

Thank you 👍

**Comment by m-laniakea** [comment]
Currently, you use the up-to-date 1.12 database, then apply the patch in this repository corresponding to the patch version you would like to have. 
However, we want to change it to a progressive system, where you start with 1.2, then add patches up to the one you want.
