### ISSUE TITLE
Elysium: Legplates of the Eternal Guardian - +defense is use rather than equip

### ISSUE THREAD

**Issue by natx91** [elysium-project/itemization#32]
On Elysium the +22 defense is as of 7/5/2017 on use rather than equip. I believe this is an error. See screenshot.

![wowscrnshot_070617_141144](https://user-images.githubusercontent.com/11026316/27910438-738f7690-6255-11e7-8b32-444e2d3cccb8.png)

**Comment by AlisterGreg** [comment]
http://db.vanillagaming.org/?item=11927 -link for anyone who is checking, looks like it should be "on equip" instead of "on use"

**Comment by cetudwakhan** [comment]
It's the same problem on Stoneform Shoulders the +10 def should be on Equipped than on Use
And Using these 2 items is impossible BTW
Thanks

**Comment by natx91** [comment]
This has been fixed on Legplates of the Eternal guardian.
